language: python
python:
  - "3.4"
  - "3.5"
# command to install dependencies
install:
  - sudo apt-get update
  - sudo apt-get install libspatialindex-dev
  - pip install -r requirements.txt
# command to run tests
script: nosetests